// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzyyuycufmlybqqwpkix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6eXl1eWN1Zm1seWJxcXdwa2l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NTk0MTUsImV4cCI6MjA3MDQzNTQxNX0.wwieyGDEcfjWSGeDrnLt7VhSfU021anmO4V2jhJKw8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});